eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
